workspace 'BeaconSDKDemo'

platform :ios, '13.0'

# Fix deployment target warnings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end

target 'BeaconSDKDemo' do
    use_frameworks!

    pod 'OctezConnectCore', :path => '../../'
    pod 'OctezConnectBlockchainTezos', :path => '../../'
    pod 'OctezConnectBlockchainSubstrate', :path => '../../'
    pod 'OctezConnectClientWallet', :path => '../../'
    pod 'OctezConnectClientDApp', :path => '../../'
    pod 'OctezConnectTransportP2PMatrix', :path => '../../'

end
